### ISSUE TITLE
Support for bintray

### ISSUE THREAD

**Issue by cheleb** [aiyanbo/sbt-dependency-updates#13]
Dependencies hosted on bintray, mainly sbt-plugins are not supported by this wonderful plugin.

There a public api: 
- All version: https://bintray.com/api/v1/search/packages?name=sbt-fresh&repo=sbt-plugins&subject=hseeberger.
- latest version: https://bintray.com/api/v1/packages/sbt/sbt-plugin-releases/sbt-fresh/versions/_latest

I would be happy to contribute if you want/need.

Thx

**Comment by aiyanbo** [comment]
@cheleb Thank for your feedback. It will be supported in the next release.

**Comment by aiyanbo** [comment]
@cheleb Bintray repo is a URLRepository in SBT.  You need add Bintray Repo to your resolvers, like this:
- Add resolver to your build.sbt
```
resolvers += Resolver.bintrayIvyRepo("sbt", "sbt-plugin-releases")
```
- Or add `~/.sbt/repositories`
```
[repositories]
  local
  maven-local
  typesafe-ivy: https://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  sbt-plugin-release: https://dl.bintray.com/sbt/sbt-plugin-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```

**Comment by aparo** [comment]
This can be closed because bintray is closed.
