### ISSUE TITLE
Package conflicts due to updates

### ISSUE THREAD

**Issue by carlosedp** [aiyanbo/sbt-dependency-updates#19]
We've seen some package conflicts related to scala-xml library. After updating the `sbt-scoverage` plugin [(ref)](https://github.com/scoverage/sbt-scoverage/issues/439), I started getting errors due to the use of scala-xml 1.2 (newer plugins started using 2.1). I tracked down to sbt-dependency-updates since it uses `scalariform` and `artifact-versions`.

```
[success] Total time: 2 s, completed Jul 27, 2022, 2:05:24 PM
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.2.0}
[error] 	    +- org.scoverage:scalac-scoverage-reporter_2.12:2.0.1 (depends on 2.1.0)
[error] 	    +- org.scalariform:scalariform_2.12:0.2.10            (depends on 1.2.0)
[error] 	    +- org.jmotor.artifact:artifact-versions_2.12:1.0.6   (depends on 1.2.0)
```

Is there anything that can be done here to mitigate this?
Thanks

**Comment by carlosedp** [comment]
I've opened:

- https://github.com/scala-ide/scalariform/pull/294
- https://github.com/aiyanbo/artifact-verions/pull/1

As they get merged and published, we can bump them here too.

**Comment by aiyanbo** [comment]
I am very sorry for taking so long to reply to you, this issue will be solved within the next two days.

**Comment by carlosedp** [comment]
Thanks!

**Comment by carlosedp** [comment]
@aiyanbo please check https://github.com/scala-ide/scalariform/pull/294#issuecomment-1206517773 comment.

**Comment by carlosedp** [comment]
Awesome! Just merged and bumped the conflicting lib as well (scoverage) and worked perfectly.
Thanks a lot, this is by far the best dependency check plugin for SBT.
