### ISSUE TITLE
why does it sort the names by length and not alphabetically?

### ISSUE THREAD

**Issue by martinpallmann** [aiyanbo/sbt-dependency-updates#9]
As a human reader I would find versions faster if they are sorted alphabetically. Maybe this could be a configuration or changed?

https://github.com/aiyanbo/sbt-dependency-updates/blob/3ed5ee8d24f68b9f933c02f8c18d39e823be2d7b/src/main/scala/org/jmotor/sbt/Updates.scala#L50

**Comment by aiyanbo** [comment]
Just considering the aesthetics of the code.

- Sort the names by length
![Untitled Diagram](https://user-images.githubusercontent.com/1162070/55848092-6b8e3700-5b7e-11e9-929b-9241bbd0ea14.png)

- Sort the names by alphabetically
![Untitled Diagram (1)](https://user-images.githubusercontent.com/1162070/55848286-fb33e580-5b7e-11e9-8c42-1f0813a5800b.png)

**Comment by martinpallmann** [comment]
I'm not so much concerned about the aesthetics but I'd like to have stable git diffs. When one version changes from 1.2 to 1.3-RELEASE or something the lines will swap and I have a headache merging a PR. So I think it would be nice to make the sorting configurable then.

**Comment by martinpallmann** [comment]
BTW thanks for that great project.

**Comment by martinpallmann** [comment]
thank you very much.

**Comment by aiyanbo** [comment]
Fixed in commit: https://github.com/aiyanbo/sbt-dependency-updates/commit/ef3634136093530fcc7b6fa8372aa9ec17629df5
